services:  
  vault-agent:
    container_name: vault-agent
    image: hashicorp/vault
    command: agent -config=/vault/config/agent-config.hcl
    env_file:
      - /etc/vault/.env
    volumes:
      - ./vault/agent-config.hcl:/vault/config/agent-config.hcl:ro
      - /etc/vault:/etc/vault
      - ./vault/templates:/etc/vault/templates
    cap_add:
      - IPC_LOCK
    profiles:
      - vault-agent

  setup-watcher:
    image: alpine:latest
    volumes:
      - ./scripts/secret-reload.sh:/tmp/secret-reload.sh:ro
      - ./scripts/cert-reload.sh:/tmp/cert-reload.sh:ro
      - ./scripts/setup-watcher.sh:/setup.sh:ro
      - /:/host 
    command: sh /setup.sh
    privileged: true
    network_mode: host
    profiles:
      - grafana

  nginx:
    image: nginx:alpine 
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    env_file: 
      - /etc/vault/secrets/.env
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/vault/certs/server.crt:/certs/server.crt:ro
      - /etc/vault/certs/server.key:/certs/server.key:ro
      - /etc/vault/ca.crt:/certs/ca.crt:ro
    depends_on:  
      - grafana
      - loki
      - prometheus
    networks:
      - alloy-net
    profiles:
      - grafana
      - reload

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    networks: 
      - alloy-net
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
      - /etc/vault/certs:/certs:ro
    command: -config.file=/etc/loki/local-config.yaml
    profiles:
      - grafana
      - reload

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
      - /etc/vault/certs:/certs:ro
    networks: 
      - alloy-net 
    profiles:
      - grafana
      - reload

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    networks: 
      - alloy-net
    env_file: 
      - /etc/vault/secrets/.env
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
      - /etc/vault/certs:/certs:ro
    profiles:
      - grafana
      - reload

  ngrok:
      image: ngrok/ngrok:latest
      container_name: ngrok
      env_file: 
        - /etc/vault/secrets/.env
      networks:
        - alloy-net
      command: http nginx:443 --domain=${NGROK_DOMAIN} --log stdout
      profiles:
        - grafana
        - reload

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  alloy-net:
    driver: bridge
